#!/usr/bin/env bash
# This script uses flameshot to interactively
# take a screenshot. You should have manga-ocr running
# in the backgorund, monitoring the right directory

# Then opens yomichan search or focuses it if
# it is already open

function usage() {
    echo "Usage: flameshot-ocr"
}

# directory that you are monitoring with manga-ocr
save_path="/home/negosaki/Pictures/ocr/flameshot-screenshot.png"

flameshot gui -r > "$save_path"
sleep 0.5
# absolute path to your yomichan-search script (the script in this repo)
/home/negosaki/bin/yomichan-search
exit 0
